-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Item CASCADE;
DROP TABLE IF EXISTS Outfit CASCADE;
DROP TABLE IF EXISTS Outfit_items CASCADE;
DROP TABLE IF EXISTS Outfit_collection CASCADE;
DROP TABLE IF EXISTS Wardrobe CASCADE;
DROP TABLE IF EXISTS Wishlist CASCADE;
DROP TABLE IF EXISTS Use_history CASCADE;