-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Item CASCADE;
DROP TABLE IF EXISTS Outfit CASCADE;
DROP TABLE IF EXISTS Outfititems CASCADE;
DROP TABLE IF EXISTS Outfitcollection CASCADE;
DROP TABLE IF EXISTS Wardrobe CASCADE;
DROP TABLE IF EXISTS Wishlist CASCADE;
DROP TABLE IF EXISTS Usehistory CASCADE;